version = 0.1
[default]
[default.build]
[default.build.parameters]
cached="true"
parallel="true"

[auth.deploy.parameters]
stack_name = "besta-api-auth"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "GoogleClientId={{GoogleClientId}}",
  "GoogleClientSecret={{GoogleClientSecret}}"
]

[api.deploy.parameters]
stack_name = "{{StackName}}"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "DBHost={{DBHost}}",
  "DBUser={{DBUser}}",
  "DBPassword={{DBPassword}}",
  "DBPort={{DBPort}}",
  "DBDatabase={{DBDatabase}}"
]
image_repositories = []
